/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  containsBytes,
  getU8Encoder,
  type Address,
  type ReadonlyUint8Array,
} from '@solana/web3.js';
import {
  type ParsedCooldownNcnVaultSlasherTicketInstruction,
  type ParsedCooldownNcnVaultTicketInstruction,
  type ParsedCooldownOperatorVaultTicketInstruction,
  type ParsedInitializeConfigInstruction,
  type ParsedInitializeNcnInstruction,
  type ParsedInitializeNcnOperatorStateInstruction,
  type ParsedInitializeNcnVaultSlasherTicketInstruction,
  type ParsedInitializeNcnVaultTicketInstruction,
  type ParsedInitializeOperatorInstruction,
  type ParsedInitializeOperatorVaultTicketInstruction,
  type ParsedNcnCooldownOperatorInstruction,
  type ParsedNcnSetAdminInstruction,
  type ParsedNcnSetSecondaryAdminInstruction,
  type ParsedNcnWarmupOperatorInstruction,
  type ParsedNcnWithdrawalAssetInstruction,
  type ParsedOperatorCooldownNcnInstruction,
  type ParsedOperatorSetAdminInstruction,
  type ParsedOperatorSetSecondaryAdminInstruction,
  type ParsedOperatorWarmupNcnInstruction,
  type ParsedOperatorWithdrawalAssetInstruction,
  type ParsedWarmupNcnVaultSlasherTicketInstruction,
  type ParsedWarmupNcnVaultTicketInstruction,
  type ParsedWarmupOperatorVaultTicketInstruction,
} from '../instructions';

export const JITO_RESTAKING_PROGRAM_PROGRAM_ADDRESS =
  '2gYZ1xHgydtzqfRuwvoL5oZmJzRo6TDQJNjuf2fARouZ' as Address<'2gYZ1xHgydtzqfRuwvoL5oZmJzRo6TDQJNjuf2fARouZ'>;

export enum JitoRestakingProgramAccount {
  Config,
  Ncn,
  NcnOperatorState,
  NcnVaultSlasherTicket,
  NcnVaultTicket,
  Operator,
  OperatorVaultTicket,
  SlotToggle,
}

export enum JitoRestakingProgramInstruction {
  InitializeConfig,
  InitializeNcn,
  InitializeOperator,
  InitializeNcnVaultSlasherTicket,
  InitializeNcnVaultTicket,
  InitializeOperatorVaultTicket,
  InitializeNcnOperatorState,
  WarmupNcnVaultTicket,
  CooldownNcnVaultTicket,
  NcnWarmupOperator,
  NcnCooldownOperator,
  OperatorWarmupNcn,
  OperatorCooldownNcn,
  WarmupNcnVaultSlasherTicket,
  CooldownNcnVaultSlasherTicket,
  WarmupOperatorVaultTicket,
  CooldownOperatorVaultTicket,
  NcnSetAdmin,
  NcnSetSecondaryAdmin,
  OperatorSetAdmin,
  OperatorSetSecondaryAdmin,
  NcnWithdrawalAsset,
  OperatorWithdrawalAsset,
}

export function identifyJitoRestakingProgramInstruction(
  instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array
): JitoRestakingProgramInstruction {
  const data = 'data' in instruction ? instruction.data : instruction;
  if (containsBytes(data, getU8Encoder().encode(0), 0)) {
    return JitoRestakingProgramInstruction.InitializeConfig;
  }
  if (containsBytes(data, getU8Encoder().encode(1), 0)) {
    return JitoRestakingProgramInstruction.InitializeNcn;
  }
  if (containsBytes(data, getU8Encoder().encode(2), 0)) {
    return JitoRestakingProgramInstruction.InitializeOperator;
  }
  if (containsBytes(data, getU8Encoder().encode(3), 0)) {
    return JitoRestakingProgramInstruction.InitializeNcnVaultSlasherTicket;
  }
  if (containsBytes(data, getU8Encoder().encode(4), 0)) {
    return JitoRestakingProgramInstruction.InitializeNcnVaultTicket;
  }
  if (containsBytes(data, getU8Encoder().encode(5), 0)) {
    return JitoRestakingProgramInstruction.InitializeOperatorVaultTicket;
  }
  if (containsBytes(data, getU8Encoder().encode(6), 0)) {
    return JitoRestakingProgramInstruction.InitializeNcnOperatorState;
  }
  if (containsBytes(data, getU8Encoder().encode(7), 0)) {
    return JitoRestakingProgramInstruction.WarmupNcnVaultTicket;
  }
  if (containsBytes(data, getU8Encoder().encode(8), 0)) {
    return JitoRestakingProgramInstruction.CooldownNcnVaultTicket;
  }
  if (containsBytes(data, getU8Encoder().encode(9), 0)) {
    return JitoRestakingProgramInstruction.NcnWarmupOperator;
  }
  if (containsBytes(data, getU8Encoder().encode(10), 0)) {
    return JitoRestakingProgramInstruction.NcnCooldownOperator;
  }
  if (containsBytes(data, getU8Encoder().encode(11), 0)) {
    return JitoRestakingProgramInstruction.OperatorWarmupNcn;
  }
  if (containsBytes(data, getU8Encoder().encode(12), 0)) {
    return JitoRestakingProgramInstruction.OperatorCooldownNcn;
  }
  if (containsBytes(data, getU8Encoder().encode(13), 0)) {
    return JitoRestakingProgramInstruction.WarmupNcnVaultSlasherTicket;
  }
  if (containsBytes(data, getU8Encoder().encode(14), 0)) {
    return JitoRestakingProgramInstruction.CooldownNcnVaultSlasherTicket;
  }
  if (containsBytes(data, getU8Encoder().encode(15), 0)) {
    return JitoRestakingProgramInstruction.WarmupOperatorVaultTicket;
  }
  if (containsBytes(data, getU8Encoder().encode(16), 0)) {
    return JitoRestakingProgramInstruction.CooldownOperatorVaultTicket;
  }
  if (containsBytes(data, getU8Encoder().encode(17), 0)) {
    return JitoRestakingProgramInstruction.NcnSetAdmin;
  }
  if (containsBytes(data, getU8Encoder().encode(18), 0)) {
    return JitoRestakingProgramInstruction.NcnSetSecondaryAdmin;
  }
  if (containsBytes(data, getU8Encoder().encode(19), 0)) {
    return JitoRestakingProgramInstruction.OperatorSetAdmin;
  }
  if (containsBytes(data, getU8Encoder().encode(20), 0)) {
    return JitoRestakingProgramInstruction.OperatorSetSecondaryAdmin;
  }
  if (containsBytes(data, getU8Encoder().encode(21), 0)) {
    return JitoRestakingProgramInstruction.NcnWithdrawalAsset;
  }
  if (containsBytes(data, getU8Encoder().encode(22), 0)) {
    return JitoRestakingProgramInstruction.OperatorWithdrawalAsset;
  }
  throw new Error(
    'The provided instruction could not be identified as a jitoRestakingProgram instruction.'
  );
}

export type ParsedJitoRestakingProgramInstruction<
  TProgram extends string = '2gYZ1xHgydtzqfRuwvoL5oZmJzRo6TDQJNjuf2fARouZ',
> =
  | ({
      instructionType: JitoRestakingProgramInstruction.InitializeConfig;
    } & ParsedInitializeConfigInstruction<TProgram>)
  | ({
      instructionType: JitoRestakingProgramInstruction.InitializeNcn;
    } & ParsedInitializeNcnInstruction<TProgram>)
  | ({
      instructionType: JitoRestakingProgramInstruction.InitializeOperator;
    } & ParsedInitializeOperatorInstruction<TProgram>)
  | ({
      instructionType: JitoRestakingProgramInstruction.InitializeNcnVaultSlasherTicket;
    } & ParsedInitializeNcnVaultSlasherTicketInstruction<TProgram>)
  | ({
      instructionType: JitoRestakingProgramInstruction.InitializeNcnVaultTicket;
    } & ParsedInitializeNcnVaultTicketInstruction<TProgram>)
  | ({
      instructionType: JitoRestakingProgramInstruction.InitializeOperatorVaultTicket;
    } & ParsedInitializeOperatorVaultTicketInstruction<TProgram>)
  | ({
      instructionType: JitoRestakingProgramInstruction.InitializeNcnOperatorState;
    } & ParsedInitializeNcnOperatorStateInstruction<TProgram>)
  | ({
      instructionType: JitoRestakingProgramInstruction.WarmupNcnVaultTicket;
    } & ParsedWarmupNcnVaultTicketInstruction<TProgram>)
  | ({
      instructionType: JitoRestakingProgramInstruction.CooldownNcnVaultTicket;
    } & ParsedCooldownNcnVaultTicketInstruction<TProgram>)
  | ({
      instructionType: JitoRestakingProgramInstruction.NcnWarmupOperator;
    } & ParsedNcnWarmupOperatorInstruction<TProgram>)
  | ({
      instructionType: JitoRestakingProgramInstruction.NcnCooldownOperator;
    } & ParsedNcnCooldownOperatorInstruction<TProgram>)
  | ({
      instructionType: JitoRestakingProgramInstruction.OperatorWarmupNcn;
    } & ParsedOperatorWarmupNcnInstruction<TProgram>)
  | ({
      instructionType: JitoRestakingProgramInstruction.OperatorCooldownNcn;
    } & ParsedOperatorCooldownNcnInstruction<TProgram>)
  | ({
      instructionType: JitoRestakingProgramInstruction.WarmupNcnVaultSlasherTicket;
    } & ParsedWarmupNcnVaultSlasherTicketInstruction<TProgram>)
  | ({
      instructionType: JitoRestakingProgramInstruction.CooldownNcnVaultSlasherTicket;
    } & ParsedCooldownNcnVaultSlasherTicketInstruction<TProgram>)
  | ({
      instructionType: JitoRestakingProgramInstruction.WarmupOperatorVaultTicket;
    } & ParsedWarmupOperatorVaultTicketInstruction<TProgram>)
  | ({
      instructionType: JitoRestakingProgramInstruction.CooldownOperatorVaultTicket;
    } & ParsedCooldownOperatorVaultTicketInstruction<TProgram>)
  | ({
      instructionType: JitoRestakingProgramInstruction.NcnSetAdmin;
    } & ParsedNcnSetAdminInstruction<TProgram>)
  | ({
      instructionType: JitoRestakingProgramInstruction.NcnSetSecondaryAdmin;
    } & ParsedNcnSetSecondaryAdminInstruction<TProgram>)
  | ({
      instructionType: JitoRestakingProgramInstruction.OperatorSetAdmin;
    } & ParsedOperatorSetAdminInstruction<TProgram>)
  | ({
      instructionType: JitoRestakingProgramInstruction.OperatorSetSecondaryAdmin;
    } & ParsedOperatorSetSecondaryAdminInstruction<TProgram>)
  | ({
      instructionType: JitoRestakingProgramInstruction.NcnWithdrawalAsset;
    } & ParsedNcnWithdrawalAssetInstruction<TProgram>)
  | ({
      instructionType: JitoRestakingProgramInstruction.OperatorWithdrawalAsset;
    } & ParsedOperatorWithdrawalAssetInstruction<TProgram>);
