/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Codec,
  type Decoder,
  type Encoder,
  type ReadonlyUint8Array,
} from '@solana/web3.js';

export type SlotToggle = {
  slotAdded: bigint;
  slotRemoved: bigint;
  reserved: ReadonlyUint8Array;
};

export type SlotToggleArgs = {
  slotAdded: number | bigint;
  slotRemoved: number | bigint;
  reserved: ReadonlyUint8Array;
};

export function getSlotToggleEncoder(): Encoder<SlotToggleArgs> {
  return getStructEncoder([
    ['slotAdded', getU64Encoder()],
    ['slotRemoved', getU64Encoder()],
    ['reserved', fixEncoderSize(getBytesEncoder(), 32)],
  ]);
}

export function getSlotToggleDecoder(): Decoder<SlotToggle> {
  return getStructDecoder([
    ['slotAdded', getU64Decoder()],
    ['slotRemoved', getU64Decoder()],
    ['reserved', fixDecoderSize(getBytesDecoder(), 32)],
  ]);
}

export function getSlotToggleCodec(): Codec<SlotToggleArgs, SlotToggle> {
  return combineCodec(getSlotToggleEncoder(), getSlotToggleDecoder());
}
