/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/web3.js';

export enum NcnAdminRole {
  OperatorAdmin,
  VaultAdmin,
  SlasherAdmin,
  DelegateAdmin,
  MetadataAdmin,
  WeightTableAdmin,
  NcnProgramAdmin,
}

export type NcnAdminRoleArgs = NcnAdminRole;

export function getNcnAdminRoleEncoder(): Encoder<NcnAdminRoleArgs> {
  return getEnumEncoder(NcnAdminRole);
}

export function getNcnAdminRoleDecoder(): Decoder<NcnAdminRole> {
  return getEnumDecoder(NcnAdminRole);
}

export function getNcnAdminRoleCodec(): Codec<NcnAdminRoleArgs, NcnAdminRole> {
  return combineCodec(getNcnAdminRoleEncoder(), getNcnAdminRoleDecoder());
}
