/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/web3.js';

export enum OperatorAdminRole {
  NcnAdmin,
  VaultAdmin,
  VoterAdmin,
  WithdrawAdmin,
  WithdrawWallet,
}

export type OperatorAdminRoleArgs = OperatorAdminRole;

export function getOperatorAdminRoleEncoder(): Encoder<OperatorAdminRoleArgs> {
  return getEnumEncoder(OperatorAdminRole);
}

export function getOperatorAdminRoleDecoder(): Decoder<OperatorAdminRole> {
  return getEnumDecoder(OperatorAdminRole);
}

export function getOperatorAdminRoleCodec(): Codec<
  OperatorAdminRoleArgs,
  OperatorAdminRole
> {
  return combineCodec(
    getOperatorAdminRoleEncoder(),
    getOperatorAdminRoleDecoder()
  );
}
