/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  combineCodec,
  getArrayDecoder,
  getArrayEncoder,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/web3.js';

export type PodU64 = { data: Array<number> };

export type PodU64Args = PodU64;

export function getPodU64Encoder(): Encoder<PodU64Args> {
  return getStructEncoder([
    ['data', getArrayEncoder(getU8Encoder(), { size: 8 })],
  ]);
}

export function getPodU64Decoder(): Decoder<PodU64> {
  return getStructDecoder([
    ['data', getArrayDecoder(getU8Decoder(), { size: 8 })],
  ]);
}

export function getPodU64Codec(): Codec<PodU64Args, PodU64> {
  return combineCodec(getPodU64Encoder(), getPodU64Decoder());
}
