#!/bin/bash

# Determine the script's location and project root
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
PROJECT_ROOT="$( cd "$SCRIPT_DIR/../" &> /dev/null && pwd )"

# Directory containing the config files
CONFIG="${PROJECT_ROOT}/config/program.env"

# Output directory for IDL files
IDL_DIR="${PROJECT_ROOT}/idl"

mkdir -p "$IDL_DIR"

source ${CONFIG}

# Run the shank idl commands
shank idl --crate-root "${PROJECT_ROOT}/restaking_sdk" -p ${RESTAKING_PROGRAM_ID} -o "${IDL_DIR}"
shank idl --crate-root "${PROJECT_ROOT}/vault_sdk" -p ${VAULT_PROGRAM_ID} -o "${IDL_DIR}"

echo "------------------------"
echo "All configurations processed."
