/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/web3.js';

export type DelegationState = {
  stakedAmount: bigint;
  enqueuedForCooldownAmount: bigint;
  coolingDownAmount: bigint;
};

export type DelegationStateArgs = {
  stakedAmount: number | bigint;
  enqueuedForCooldownAmount: number | bigint;
  coolingDownAmount: number | bigint;
};

export function getDelegationStateEncoder(): Encoder<DelegationStateArgs> {
  return getStructEncoder([
    ['stakedAmount', getU64Encoder()],
    ['enqueuedForCooldownAmount', getU64Encoder()],
    ['coolingDownAmount', getU64Encoder()],
  ]);
}

export function getDelegationStateDecoder(): Decoder<DelegationState> {
  return getStructDecoder([
    ['stakedAmount', getU64Decoder()],
    ['enqueuedForCooldownAmount', getU64Decoder()],
    ['coolingDownAmount', getU64Decoder()],
  ]);
}

export function getDelegationStateCodec(): Codec<
  DelegationStateArgs,
  DelegationState
> {
  return combineCodec(getDelegationStateEncoder(), getDelegationStateDecoder());
}
