/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/web3.js';
import {
  getPodU64Decoder,
  getPodU64Encoder,
  type PodU64,
  type PodU64Args,
} from '.';

export type SlotToggle = { slotAdded: PodU64; slotRemoved: PodU64 };

export type SlotToggleArgs = { slotAdded: PodU64Args; slotRemoved: PodU64Args };

export function getSlotToggleEncoder(): Encoder<SlotToggleArgs> {
  return getStructEncoder([
    ['slotAdded', getPodU64Encoder()],
    ['slotRemoved', getPodU64Encoder()],
  ]);
}

export function getSlotToggleDecoder(): Decoder<SlotToggle> {
  return getStructDecoder([
    ['slotAdded', getPodU64Decoder()],
    ['slotRemoved', getPodU64Decoder()],
  ]);
}

export function getSlotToggleCodec(): Codec<SlotToggleArgs, SlotToggle> {
  return combineCodec(getSlotToggleEncoder(), getSlotToggleDecoder());
}
