/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/web3.js';

export enum VaultAdminRole {
  DelegationAdmin,
  OperatorAdmin,
  NcnAdmin,
  SlasherAdmin,
  CapacityAdmin,
  FeeWallet,
  MintBurnAdmin,
  DelegateAssetAdmin,
  FeeAdmin,
  MetadataAdmin,
}

export type VaultAdminRoleArgs = VaultAdminRole;

export function getVaultAdminRoleEncoder(): Encoder<VaultAdminRoleArgs> {
  return getEnumEncoder(VaultAdminRole);
}

export function getVaultAdminRoleDecoder(): Decoder<VaultAdminRole> {
  return getEnumDecoder(VaultAdminRole);
}

export function getVaultAdminRoleCodec(): Codec<
  VaultAdminRoleArgs,
  VaultAdminRole
> {
  return combineCodec(getVaultAdminRoleEncoder(), getVaultAdminRoleDecoder());
}
