/**
 * This code was AUTOGENERATED using the codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getEnumDecoder,
  getEnumEncoder,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/web3.js';

export enum WithdrawalAllocationMethod {
  Greedy,
}

export type WithdrawalAllocationMethodArgs = WithdrawalAllocationMethod;

export function getWithdrawalAllocationMethodEncoder(): Encoder<WithdrawalAllocationMethodArgs> {
  return getEnumEncoder(WithdrawalAllocationMethod);
}

export function getWithdrawalAllocationMethodDecoder(): Decoder<WithdrawalAllocationMethod> {
  return getEnumDecoder(WithdrawalAllocationMethod);
}

export function getWithdrawalAllocationMethodCodec(): Codec<
  WithdrawalAllocationMethodArgs,
  WithdrawalAllocationMethod
> {
  return combineCodec(
    getWithdrawalAllocationMethodEncoder(),
    getWithdrawalAllocationMethodDecoder()
  );
}
