title: Jito Restaking Documentation
description: Jito Restaking Documentation
url: "https://docs.restaking.jito.network"

markdown: kramdown
remote_theme: sighingnow/jekyll-gitbook
syntax_highlighter_style: colorful
