title: Jito Restaking Documentation
longtitle: Jito Restaking Documentation
description: Jito Restaking Documentation
url: "https://docs.restaking.jito.network"

remote_theme: sighingnow/jekyll-gitbook

markdown: kramdown
syntax_highlighter_style: colorful

toc:
    enabled: true

assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - assets

collections:
  pages:
    output: true
    permalink: /:collection/:path/
    order:
      - terminology.md
      - restaking_accounts.md
      - restaking_theory_of_operation.md
      - vault_accounts.md
      - vault_theory_of_operation.md
      - building_vrt.md
      - building_ncn.md

ordered_collections:
  - pages