title: Jito Restaking Documentation
longtitle: Jito Restaking Documentation
description: Jito Restaking Documentation
url: "https://docs.restaking.jito.network"

remote_theme: sighingnow/jekyll-gitbook

markdown: kramdown
syntax_highlighter_style: colorful

toc:
    enabled: true

assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - assets

collections:
  about:
    output: true
    permalink: /:collection/:path/
    sort_by: weight
  restaking:
    output: true
    permalink: /:collection/:path/
    sort_by: weight
  vault:
    output: true
    permalink: /:collection/:path/
    sort_by: weight
  advanced:
    output: true
    permalink: /:collection/:path/
    sort_by: weight
  tools:
    output: true
    permalink: /:collection/:path/
    sort_by: weight

ordered_collections:
  - about
  - restaking
  - vault
  - tools
  - advanced
