title: Jito Restaking Documentation
longtitle: Jito Restaking Documentation
description: Jito Restaking Documentation
url: "https://docs.restaking.jito.network"

remote_theme: sighingnow/jekyll-gitbook

markdown: kramdown
syntax_highlighter_style: colorful

toc:
    enabled: true

assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - assets

collections:
  posts:
    output: true
    permalink: /:collection/:path/

ordered_collections:
  - posts