title: Jito Restaking Documentation
longtitle: Jito Restaking Documentation
description: Jito Restaking Documentation
url: "https://docs.restaking.jito.network"

remote_theme: sighingnow/jekyll-gitbook

# markdown: kramdown
# syntax_highlighter_style: colorful
